WIP feature: add job to test connectivity to tcp service
Kong/kubernetes-testing-framework pull request #336
Opened 2022-08-01 09:51 UTC by randmonkey

Try to add a job to test connectivity to a TCP service inside a k8s cluster. 
TODO:
- push the tcptest image to kong repo
- add more parameters for testing
- discuss about other kinds of "tests", http/https/tls/udp ?

2022-08-01 09:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/kubernetes-testing-framework?pullRequest=336) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/kubernetes-testing-framework?pullRequest=336) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/kubernetes-testing-framework?pullRequest=336) it.</sub>

2022-08-02 13:13 UTC, shaneutt requested changes
I'm really not sure about this approach. Last we had talked I thought we were going to add a tool that deploys a temporary `LoadBalancer` type `Service` to the cluster, so that in this way we can just test using the Go library and not need a new image and all this other stuff.

What was wrong with the `LoadBalancer` approach?

2022-08-03 09:26 UTC, randmonkey commented
> I'm really not sure about this approach. Last we had talked I thought we were going to add a tool that deploys a temporary `LoadBalancer` type `Service` to the cluster, so that in this way we can just test using the Go library and not need a new image and all this other stuff.
> 
> What was wrong with the `LoadBalancer` approach?

The reason why I proposed this approach (OR, the cons for `LoadBalancer` approach): 
- `LoadBalancer` may not be supported by all kinds of clusters. If a cluster does not provide a `LoadBalancer` service, the temp lb solution could not be used.
- The new temporary service is not exactly the same thing as the original one. So the result may not be 100% prove that the original service could/could not be accessed. 

Cons for this approach:
 - We need to maintain extra code and image to deploy the jobs inside cluster.

The `LoadaBalancer` solution is here: #338. We could consider which solution would be accepted.

2022-08-03 17:58 UTC, shaneutt commented
In a testing environment we _control the cluster environment_ and can guarantee `LoadBalancer` functionality is available, and additionally that deals with the problem utilizing Kubernetes native APIs that can be injected into any test rather than a job that needs to be maintained as a separate tool. I am highly in favor of us taking the `LoadBalancer` approach instead for these reasons.

2022-08-04 05:53 UTC, closed without merging